# Generated by Django 3.2.8 on 2021-10-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('lang', models.CharField(max_length=200)),
                ('birth_date', models.DateField(default=0)),
            ],
        ),
    ]
