# Generated by Django 3.2.8 on 2021-10-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='step',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
