# Generated by Django 3.2.8 on 2021-10-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_user_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
