# Generated by Django 3.2.8 on 2021-10-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_user_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='izoh',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
